services:
  dataselfcloud-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: dataselfcloud-mysql
    image: dataselfcloud-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  dataselfcloud-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: dataselfcloud-redis
    hostname: dataselfcloud-redis
    networks:
      - spring_cloud_default

  dataselfcloud-register:
    build:
      context: ./dataselfcloud-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 8080:8080
    environment:
      MYSQL_HOST: dataselfcloud-mysql
      REDIS_HOST: dataselfcloud-redis
    container_name: dataselfcloud-register
    hostname: dataselfcloud-register
    image: dataselfcloud-register
    networks:
      - spring_cloud_default

  dataselfcloud-gateway:
    build:
      context: ./dataselfcloud-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: dataselfcloud-gateway
    hostname: dataselfcloud-gateway
    image: dataselfcloud-gateway
    environment:
      REDIS_HOST: dataselfcloud-redis
      NACOS_HOST: dataselfcloud-register
    networks:
      - spring_cloud_default

  dataselfcloud-auth:
    build:
      context: ./dataselfcloud-auth
    restart: always
    container_name: dataselfcloud-auth
    hostname: dataselfcloud-auth
    image: dataselfcloud-auth
    environment:
      REDIS_HOST: dataselfcloud-redis
      NACOS_HOST: dataselfcloud-register
    networks:
      - spring_cloud_default

  dataselfcloud-upms:
    build:
      context: ./dataselfcloud-upms/dataselfcloud-upms-biz
    restart: always
    container_name: dataselfcloud-upms
    hostname: dataselfcloud-upms
    image: dataselfcloud-upms
    environment:
      MYSQL_HOST: dataselfcloud-mysql
      REDIS_HOST: dataselfcloud-redis
      NACOS_HOST: dataselfcloud-register
    networks:
      - spring_cloud_default

  dataselfcloud-monitor:
    build:
      context: ./dataselfcloud-visual/dataselfcloud-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: dataselfcloud-monitor
    hostname: dataselfcloud-monitor
    image: dataselfcloud-monitor
    environment:
      NACOS_HOST: dataselfcloud-register
    networks:
      - spring_cloud_default

  dataselfcloud-codegen:
    build:
      context: ./dataselfcloud-visual/dataselfcloud-codegen
    restart: always
    container_name: dataselfcloud-codegen
    hostname: dataselfcloud-codegen
    image: dataselfcloud-codegen
    environment:
      MYSQL_HOST: dataselfcloud-mysql
      REDIS_HOST: dataselfcloud-redis
      NACOS_HOST: dataselfcloud-register
    networks:
      - spring_cloud_default

  dataselfcloud-quartz:
    build:
      context: ./dataselfcloud-visual/dataselfcloud-quartz
    restart: always
    image: dataselfcloud-quartz
    container_name: dataselfcloud-quartz
    environment:
      MYSQL_HOST: dataselfcloud-mysql
      REDIS_HOST: dataselfcloud-redis
      NACOS_HOST: dataselfcloud-register
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
